### ISSUE TITLE
repr() fails

### ISSUE THREAD

**Issue by abg** [oleiade/durations#4]
``` python

>>> from durations import Duration
>>> Duration("1hour")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "durations/duration.py", line 42, in __repr__
    return self.__str__()
  File "durations/duration.py", line 39, in __str__
    return '<Duration {}>'.format(self.representation)
AttributeError: 'Duration' object has no attribute 'representation'
```

**Comment by oleiade** [comment]
Hotfixed and published in a 0.3.1 bugfixes version disposable on pypi. Thanks for the bug hunting !
